ajar/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), ),
    path('anime/', include('anime.urls'), ),
    path('anime/info/', include('info.urls'),),
    path('anime/play/', include('play.urls'),),
    path('schedule/', include('schedule.urls'), ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'home.views.error_404'
handler403 = 'home.views.error_404'
handler500 = 'home.views.error_404'
handler400 = 'home.views.error_404'

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.index, name='ajar_home'),
    path('error404/', views.error_404, name='error_404'),
    path('results/', views.search, name='search'),
    path('catlog/<cat_item>', views.catlog, name='catlog'),
]

home/models.py
from django.db import models


class PopularAnime(models.Model):
    class Meta:
        db_table = 'popular'
    cover = models.CharField(max_length=200, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    anime_id = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        template = '{0.name}'
        return template.format(self)

home/views.py
from django.shortcuts import render

from django.apps import apps
from .models import PopularAnime
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.core.paginator import Paginator
importing_info = apps.get_model('info', 'Anime')
from django.apps import apps
importing_episode = apps.get_model('play', 'Episode')
# Create your views here.


def index(request,):
    anime_info = importing_info.objects.order_by('?')[:9]
    anime_top = importing_info.objects.order_by('-scores')[:9]
    popular = PopularAnime.objects.order_by('-id')[:9]
    random = importing_info.objects.order_by('?')[:15]
    random_search = importing_info.objects.order_by('?')[:1]
    episode = importing_episode.objects.order_by('-id')[:60]
    paginator = Paginator(episode, 12)
    page = request.GET.get('page')
    episode_data = paginator.get_page(page)
    context = {
        'random': random,
        'random_search': random_search,
        'episode_data': episode_data,
        'anime_info': anime_info,
        'popular': popular,
        'anime_top': anime_top,
    }
    return render(request, 'home/index.html', context)


def search(request):
    template = 'home/search.html'
    queryset_list = importing_info.objects.all()
    query = request.GET.get('q')
    if query == '':
        return HttpResponseRedirect('/')
    else:
        if query:
            queryset_list = queryset_list.filter(
                Q(name__icontains=query) |
                Q(tags__icontains=query) |
                Q(gener__icontains=query)
            ).order_by('-scores')
            random_search = importing_info.objects.order_by('?')[:1]
            paginator = Paginator(queryset_list, 30)
            page = request.GET.get('page')
            result = paginator.get_page(page)
            context = {
                'result': result,
                'random_search': random_search,
            }
            return render(request, template, context)
        else:
            messages.error(request, 'no results found')

    # if request.method == 'POST':
    #     query = request.POST['q']
    #     if query:
    #         match = importing_info.objects.filter(Q(name__icontains=query)).order_by('-scores')
    #         if match:
    #             paginator = Paginator(match, 12)
    #             page = request.GET.get('page')
    #             result = paginator.get_page(page)
    #             return render(request, template, {'result': result})
    #         else:
    #             messages.error(request, 'no results found')
    #     else:
    #         return HttpResponseRedirect('/')


def catlog(request, cat_item):
    template = 'home/catlog.html'
    queryset_list = importing_info.objects.all()
    query = cat_item
    if query == '':
        return HttpResponseRedirect('/')
    else:
        if query:
            queryset_list = queryset_list.filter(
                Q(gener__icontains=query)
            ).order_by('-scores')
            random_search = importing_info.objects.order_by('?')[:1]
            paginator = Paginator(queryset_list, 30)
            page = request.GET.get('page')
            result = paginator.get_page(page)
            context = {
                'result': result,
                'random_search': random_search,
            }
            return render(request, template, context)
        else:
            messages.error(request, 'no results found')


def error_404(request):
        anime_info = importing_info.objects.order_by('?')[:9]
        anime_top = importing_info.objects.order_by('-scores')[:9]
        popular = PopularAnime.objects.order_by('-id')[:9]
        random = importing_info.objects.order_by('?')[:15]
        random_search = importing_info.objects.order_by('?')[:1]
        episode = importing_episode.objects.order_by('-id')[:60]
        paginator = Paginator(episode, 12)
        page = request.GET.get('page')
        episode_data = paginator.get_page(page)
        context = {
            'random': random,
            'random_search': random_search,
            'episode_data': episode_data,
            'anime_info': anime_info,
            'popular': popular,
            'anime_top': anime_top,
        }
        return render(request, 'home/error404.html', context)

home/templates/home/error404.html
{% extends 'home/index.html' %}
{% block title %} Ajarani |  {{episode.episode}} {% endblock %}
{% block meta_data %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="csrf-token" content="">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="application-name" content="Ajarani,ajar,Ajar">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Ajarani,ajar,Ajar">
        <meta name="msapplication-TileColor" content="#171717">
        <meta name="theme-color" content="#171717">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<style>
    /* Styles of the 404 page of my website. */

.error_body {
    background: #081421;
    color: #d3d7de;
    font-family: "Courier new";
    font-size: 18px;
    line-height: 1.5em;
	cursor: default;
}

.error_body a {
	color: #fff;
	text-decoration: line-through;
}
.error_body a:hover{
       color: red;
	text-decoration: none;
}

.error_body .code-area {
    position: absolute;
    width: 320px;
	min-width: 320px;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

.error_body .code-area > span {
    display: block;
}

@media screen and (max-width: 320px) {
   .error_body  .code-area {
		font-size: 5vw;
		min-width: auto;
        width: 95%;
		margin: auto;
		padding: 5px;
		padding-left: 10px;
		line-height: 6.5vw;
    }
}

</style>
{% endblock %}

 {% block main_content %}
        <main class="mdl-layout__content">
          <div class="page-content">
              <div class="error_body">
           <div class="code-area">
              <span style="color: #777;font-style:italic;">
                // 404 page not found.
              </span>
              <span>
                <span style="color:#d65562;">
                  if
                </span>
                  (<span style="color:#4ca8ef;">!</span><span style="font-style: italic;color:#bdbdbd;">found</span>)
                {
              </span>
              <span>
                <span style="padding-left: 15px;color:#2796ec">
                   <i style="width: 10px;display:inline-block"></i>throw
                </span>
                <span>
                  (<span style="color: #a6a61f">"Error 404"</span>);<br>
                </span>
                  <span style="display:block">}</span>
                    <span style="color: #a6a61f">"Options"</span>:<br>
                  <span style="color: #777;font-style:italic;">
                      { <br>
                       <span style="color: #a6a61f">"Go To Back Page"</span>: <a style="cursor:pointer" onclick='goBack()'>Go back,</a><br>
                      <span style="color: #a6a61f">"Go Home"</span>: <a href="{% url 'home:ajar_home' %}">Go home,</a><br>

                      }
                  </span>
              </span>
            </div>
              </div>
          </div>
            <script>
            function goBack() {
              window.history.go(-1);
            }
            </script>
        </main>
                  {% endblock %}
              <!--block ended before a level of div and main-->
          <!--</div>-->
        <!--</main>-->